extraction:
  cpp:
    after_prepare: 
      - python report.py 43
  cobol:
    after_prepare: 
      - python report.py 43
  csharp:
    after_prepare: 
      - python report.py 43
  java:
    after_prepare: 
      - python report.py 43
  javascript:
    after_prepare: 
      - python report.py 43
  python:
    after_prepare: 
      - python report.py 43
